---
- name: add the service group
  group:
    name: svc
    state: present

- name: add the service user
  user:
    name: zookeeper
    groups: svc
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "Service User"
    state: present

- name: install zk
  include_role:
    name: install-1.0.0
  vars:
    opts:
      pkg_name: zookeeper
      pkg_version: "{{ zk_version }}"
      pkg_url: https://mirror.bit.edu.cn/apache/zookeeper/zookeeper-{{ zk_version }}/zookeeper-{{ zk_version }}.tar.gz
      pkg_type: .tgz
      extracts: true
      bin_path: bin
      creates: bin/zkServer.sh

- name: set up zkrest dir
  file:
    path: /opt/zkrest
    state: directory

- name: set up zkrest files
  file:
    src: /opt/zookeeper/current/zookeeper-contrib/zookeeper-contrib-rest
    dest: /opt/zkrest/current
    state: link

- name: link necessary zk jar files to bootstrap zkrest
  file:
    src: /opt/zookeeper/current/{{ file_path }}
    dest: /opt/zkrest/current/{{ file_path }}
    state: link
  loop:
  - zookeeper-{{ zk_version }}.jar
  loop_control:
    loop_var: file_path

- name: install services
  copy:
    src: roles/{{ role_name }}/files/lib/systemd/system/
    dest: /lib/systemd/system/

- name: mask services
  systemd:
    name: "{{ service_name }}"
    enabled: no
    masked: yes
    state: stopped
  loop:
  - zookeeper
  - zkrest
  loop_control:
    loop_var: service_name

- name: copy files
  copy:
    src: files/opt/
    dest: /opt/
    owner: root
    group: svc
    mode: preserve
    directory_mode: u=rwx,g=rx,o=

- name: set up zk env
  copy:
    dest: /opt/app/bin/envs/confd.env
    content: |
      ZK_VERSION={{ zk_version }}

- name: install confd files
  include_role:
    name: confd-files-1.0.2
