---
- name: zk tasks
  hosts: all
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  tasks:
  - include_role:
      name: "{{ name }}"
    loop:
    - update-apt-sources-1.0.0
    - disable-apt-jobs-1.0.0
    - disable-motd-1.0.0
    - app-agent-1.0.1
    - appctl-1.1.0
    - arping-1.0.0
    - caddy-1.0.6
    - java-1.0.1
    - jq-1.0.3
    - netcat-openbsd-1.0.0
    - zookeeper
    loop_control:
      loop_var: name
